version: "3.9"
services:
  app:
    container_name: rakuni-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./rakuni-app  # ローカルのrakuni-appディレクトリ
        target: /usr/src/app  # コンテナ内の作業ディレクトリ
    command: npm start
    ports:
      - "3000:3000"
    stdin_open: true